### ISSUE TITLE
Using model with basic data frame - Pandas dataframe

### ISSUE THREAD

**Issue by andrewczgithub** [Gordonjo/versa#2]
Hi @Gordonjo 
really cool model.
I was just wondering If i had a plain univariate pandas data frame.
How would use the model to do a basic regression
With x being time and y being values.

Cheers,
Andrew

**Comment by Gordonjo** [comment]
Hi @andrewczgithub 
Thank you very much for your interest in our model! We’re glad you find it cool :)
The purpose of this repo is to reproduce the classification and ShapeNet experiments in the paper, and so it does not support data conversion or regression problems. Generally speaking, you would need to first convert your dataframe to TensorFlow tensors to work with the model. For regression, you would need to derive the form of the appropriate model, though this should not be too difficult, and in fact, I suspect can be done in closed form! Our paper should provide all the required details to do so.
I am closing this issue, as I do not think either of these are functionalities that we are looking for in this repository. Please feel free to contact me directly if you have any questions about the model.
Cheers,
Jonathan
