### ISSUE TITLE
License for reconstruction dataset, dataset use term

### ISSUE THREAD

**Issue by gaobaoding** [Gordonjo/versa#3]
Dear authors,

Since the reconstruction dataset is not directly under this repo, I'm concerning if we can use this dataset freely or under which condition. So could you give the same license to the dataset? Or for example include a line which explicitly contain the dataset use term inside inside the license etc.. Many thanks!

**Comment by jfb54** [comment]
Added a statement in the Data section of the README explaining that users of the ShapeNet data must abide by the ShapeNet Terms of Use.
